/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import javax.swing.JOptionPane;
import java.awt.GridLayout;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;

import Modelo.Cliente;
import Modelo.Producto;
import Modelo.Insumo;
import Modelo.Proveedor;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author alulab14
 */
public class AdministracionDeReportes extends javax.swing.JFrame {

    /**
     * Creates new form AdministracionDeReportes
     */ 
    
    protected JComponent makeTextPanel(String text) {
        JPanel panel = new JPanel(false);
        JLabel filler = new JLabel(text);
        filler.setHorizontalAlignment(JLabel.CENTER);
        panel.setLayout(new GridLayout(1, 1));
        panel.add(filler);
        return panel;
    }
    public AdministracionDeReportes() throws Exception{
        initComponents();
        ArrayList<Cliente> lClientes = new ArrayList<Cliente>();
        ArrayList<Insumo> lInsumo = new ArrayList<Insumo>();
        ArrayList<Producto> lProducto = new ArrayList<Producto>();
        ArrayList<Proveedor> lProveedor = new ArrayList<Proveedor>();
        
        lClientes.add(new Cliente("yo@gmail.com","01532515","Juan Perez","Natural"));
        lClientes.add(new Cliente("yo@gmail.com","01532515","Kalor Perez","Natural"));
        lClientes.add(new Cliente("yo@gmail.com","01532515","Yuu Rodriguez","Natural"));
        lClientes.add(new Cliente("yo@gmail.com","01532515","Yui Hirata","Natural"));
        lClientes.add(new Cliente("yo@gmail.com","01532515","Mateo Santiago","Natural"));
        lClientes.add(new Cliente("yo@gmail.com","01532515","Maria Tirs SAC","Juridica"));
        
        
        lInsumo.add(new Insumo("Tela Negra","Tela Negra grosor medio",45.5,10));
        lInsumo.add(new Insumo("Tela Blanca","Tela Blanca grosor medio",45.5,10));
        lInsumo.add(new Insumo("Tela Azul","Tela Azul grosor medio",45.5,10));
        lInsumo.add(new Insumo("Tela Roja","Tela Roja grosor medio",45.5,10));
        lInsumo.add(new Insumo("Tela Verde","Tela Verde grosor medio",45.5,10));
        
        lProducto.add(new Producto("Polo azul estampado",(float) 56.2,10));
        lProducto.add(new Producto("Polo negro estampado",(float) 56.2,10));
        lProducto.add(new Producto("Polo blanco",(float) 56.2,10));
        lProducto.add(new Producto("Polo rojo estampado",(float) 56.2,10));
        lProducto.add(new Producto("Polo verde",(float) 56.2,10));
        lProducto.add(new Producto("Polo azul",(float) 56.2,10));
        
        lProveedor.add(new Proveedor("","Telas Negras SAC",null,"","","","3467589242"));
        lProveedor.add(new Proveedor("","Telas Blancas SAC",null,"","","","3435789624"));
        lProveedor.add(new Proveedor("","Agapito CAS",null,"","","","6134297586"));
        lProveedor.add(new Proveedor("","Rosatel SAC",null,"","","","3457281965"));
        lProveedor.add(new Proveedor("","Algodon Rosado SAC",null,"","","","7518264819"));
        lProveedor.add(new Proveedor("","Cinta metrica SAC",null,"","","","4653791826"));
        
        
        
        DefaultTableModel modelo = (DefaultTableModel) listaClientesVT.getModel();
        DefaultTableModel modelo2 = (DefaultTableModel) listaProveedoresCT.getModel();
        DefaultTableModel modelo3 = (DefaultTableModel) listaInsumosRC.getModel();
        DefaultTableModel modelo4 = (DefaultTableModel) listaProductosRC.getModel();
        
        Object[] fila = new Object[2];
        for(int i=0; i<lClientes.size();i++){
            fila[0] = lClientes.get(i).getName();
            fila[1] = lClientes.get(i).getTipoCliente();
            modelo.addRow(fila);
        }
        
        Object[] fila2 = new Object[1];
        for(int i=0; i<lInsumo.size();i++){
            fila2[0] = lInsumo.get(i).getNombreInsumo();
            modelo3.addRow(fila2);
        }
        
        Object[] fila3 = new Object[1];
        for(int i=0; i<lProducto.size();i++){
            fila3[0] = lProducto.get(i).getDescripcion();
            modelo4.addRow(fila3);
        }
        
        Object[] fila4 = new Object[2];
        for(int i=0; i<lProveedor.size();i++){
            fila4[0] = lProveedor.get(i).getNombre();
            fila4[1] = lProveedor.get(i).getRUC();
            modelo2.addRow(fila4);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        MejoresClientes = new javax.swing.JPanel();
        maxClientes = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        MasVendidos = new javax.swing.JPanel();
        maxInsumos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        maxProductos = new javax.swing.JTextField();
        ComprasTotales = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        diaIniCT = new javax.swing.JComboBox<>();
        mesIniCT = new javax.swing.JComboBox<>();
        anioIniCT = new javax.swing.JComboBox<>();
        diaFinCT = new javax.swing.JComboBox<>();
        mesFinCT = new javax.swing.JComboBox<>();
        anioFinCT = new javax.swing.JComboBox<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        listaProveedoresCT = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        VentasTotales = new javax.swing.JPanel();
        diaIniVT = new javax.swing.JComboBox<>();
        mesIniVT = new javax.swing.JComboBox<>();
        anioIniVT = new javax.swing.JComboBox<>();
        diaFinVT = new javax.swing.JComboBox<>();
        mesFinVT = new javax.swing.JComboBox<>();
        anioFinVT = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listaClientesVT = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        ReporteContable = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        diaIniRC = new javax.swing.JComboBox<>();
        diaFinRC = new javax.swing.JComboBox<>();
        mesIniRC = new javax.swing.JComboBox<>();
        mesFinRC = new javax.swing.JComboBox<>();
        anioIniRC = new javax.swing.JComboBox<>();
        anioFinRC = new javax.swing.JComboBox<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        listaProductosRC = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        listaInsumosRC = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        MostrarReporte = new javax.swing.JButton();
        ExportarReporte = new javax.swing.JButton();
        atrasAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Máximo de Clientes");

        javax.swing.GroupLayout MejoresClientesLayout = new javax.swing.GroupLayout(MejoresClientes);
        MejoresClientes.setLayout(MejoresClientesLayout);
        MejoresClientesLayout.setHorizontalGroup(
            MejoresClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MejoresClientesLayout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(84, 84, 84)
                .addComponent(maxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        MejoresClientesLayout.setVerticalGroup(
            MejoresClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MejoresClientesLayout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addGroup(MejoresClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(311, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mejores Clientes", MejoresClientes);

        jLabel4.setText("Maximo Número de Insumos");

        jLabel5.setText("Maximo Número de Productos");

        javax.swing.GroupLayout MasVendidosLayout = new javax.swing.GroupLayout(MasVendidos);
        MasVendidos.setLayout(MasVendidosLayout);
        MasVendidosLayout.setHorizontalGroup(
            MasVendidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MasVendidosLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(MasVendidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5))
                .addGap(67, 67, 67)
                .addGroup(MasVendidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        MasVendidosLayout.setVerticalGroup(
            MasVendidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MasVendidosLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(MasVendidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(maxInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(129, 129, 129)
                .addGroup(MasVendidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(maxProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(244, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mas Vendidos", MasVendidos);

        jLabel6.setText("Fecha Inicial");

        jLabel7.setText("Fecha Final");

        diaIniCT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        diaIniCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaIniCTActionPerformed(evt);
            }
        });

        mesIniCT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Set", "Oct", "Nov", "Dic" }));

        anioIniCT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018" }));

        diaFinCT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        mesFinCT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Set", "Oct", "Nov", "Dic" }));

        anioFinCT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018" }));

        listaProveedoresCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "RUC"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(listaProveedoresCT);

        jLabel10.setText("Seleccionar Proveedores Disponibles");

        javax.swing.GroupLayout ComprasTotalesLayout = new javax.swing.GroupLayout(ComprasTotales);
        ComprasTotales.setLayout(ComprasTotalesLayout);
        ComprasTotalesLayout.setHorizontalGroup(
            ComprasTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComprasTotalesLayout.createSequentialGroup()
                .addGroup(ComprasTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ComprasTotalesLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(ComprasTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ComprasTotalesLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(diaFinCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ComprasTotalesLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(diaIniCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(ComprasTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mesFinCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mesIniCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ComprasTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(anioIniCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(anioFinCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ComprasTotalesLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(ComprasTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        ComprasTotalesLayout.setVerticalGroup(
            ComprasTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComprasTotalesLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(ComprasTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(diaIniCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesIniCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anioIniCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(ComprasTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(diaFinCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesFinCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anioFinCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Compras Totales", ComprasTotales);

        diaIniVT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        diaIniVT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaIniVTActionPerformed(evt);
            }
        });

        mesIniVT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Set", "Oct", "Nov", "Dic" }));
        mesIniVT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesIniVTActionPerformed(evt);
            }
        });

        anioIniVT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018" }));

        diaFinVT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        mesFinVT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Set", "Oct", "Nov", "Dic" }));

        anioFinVT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018" }));

        jLabel2.setText("Fecha Inicial");

        jLabel3.setText("Fecha Final");

        listaClientesVT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo Cliente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(listaClientesVT);

        jLabel11.setText("Seleccionar Clientes Disponibles");

        javax.swing.GroupLayout VentasTotalesLayout = new javax.swing.GroupLayout(VentasTotales);
        VentasTotales.setLayout(VentasTotalesLayout);
        VentasTotalesLayout.setHorizontalGroup(
            VentasTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentasTotalesLayout.createSequentialGroup()
                .addGroup(VentasTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VentasTotalesLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(VentasTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VentasTotalesLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(diaIniVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(mesIniVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(anioIniVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(VentasTotalesLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(26, 26, 26)
                                .addComponent(diaFinVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(mesFinVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(anioFinVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(VentasTotalesLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(VentasTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        VentasTotalesLayout.setVerticalGroup(
            VentasTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentasTotalesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(VentasTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diaIniVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesIniVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anioIniVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(46, 46, 46)
                .addGroup(VentasTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(diaFinVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesFinVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anioFinVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ventas Totales", VentasTotales);

        jLabel8.setText("Fecha Inicial");
        jLabel8.setMaximumSize(new java.awt.Dimension(60, 14));
        jLabel8.setMinimumSize(new java.awt.Dimension(60, 14));

        jLabel9.setText("Fecha Final");
        jLabel9.setMaximumSize(new java.awt.Dimension(60, 14));
        jLabel9.setMinimumSize(new java.awt.Dimension(60, 14));

        diaIniRC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        diaIniRC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaIniRCActionPerformed(evt);
            }
        });

        diaFinRC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        mesIniRC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Set", "Oct", "Nov", "Dic" }));

        mesFinRC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Set", "Oct", "Nov", "Dic" }));

        anioIniRC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018" }));

        anioFinRC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018" }));

        listaProductosRC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(listaProductosRC);

        listaInsumosRC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane9.setViewportView(listaInsumosRC);

        jLabel12.setText("Seleccionar Productos Disponibles");

        jLabel13.setText("Seleccionar Insumos Disponibles");

        javax.swing.GroupLayout ReporteContableLayout = new javax.swing.GroupLayout(ReporteContable);
        ReporteContable.setLayout(ReporteContableLayout);
        ReporteContableLayout.setHorizontalGroup(
            ReporteContableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReporteContableLayout.createSequentialGroup()
                .addGroup(ReporteContableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReporteContableLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(ReporteContableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ReporteContableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ReporteContableLayout.createSequentialGroup()
                                .addComponent(diaFinRC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(mesFinRC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ReporteContableLayout.createSequentialGroup()
                                .addComponent(diaIniRC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(mesIniRC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(ReporteContableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(anioFinRC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(anioIniRC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ReporteContableLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ReporteContableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ReporteContableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        ReporteContableLayout.setVerticalGroup(
            ReporteContableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReporteContableLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(ReporteContableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diaIniRC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesIniRC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anioIniRC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(ReporteContableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesFinRC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anioFinRC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diaFinRC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(ReporteContableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(29, 29, 29)
                .addGroup(ReporteContableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reporte Contable", ReporteContable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        MostrarReporte.setText("Mostrar Reporte");
        MostrarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarReporteActionPerformed(evt);
                MostrarReporteActionPerformed1(evt);
            }
        });

        ExportarReporte.setText("Exportar Reporte");
        ExportarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportarReporteActionPerformed(evt);
            }
        });

        atrasAR.setText("Atras");
        atrasAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(MostrarReporte)
                .addGap(30, 30, 30)
                .addComponent(ExportarReporte)
                .addGap(41, 41, 41)
                .addComponent(atrasAR)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MostrarReporte)
                    .addComponent(ExportarReporte)
                    .addComponent(atrasAR))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MostrarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarReporteActionPerformed
        // TODO add your handling code here:
        if(MejoresClientes.isShowing()){
            String numD = maxClientes.getText();
            if(numD == null || numD.equals("")){
                JOptionPane.showMessageDialog(null, "Ingrese los datos correspondientes");
            }else{
                int numDatos = Integer.parseInt(numD);
                MejoresClientes rep = new MejoresClientes(null,true,numDatos);
                rep.setVisible(true);
            }
        
        }else if(MasVendidos.isShowing()){    
            String maxI = maxInsumos.getText();
            String maxP =maxProductos.getText();
            if(maxI == null || maxI.equals("") || maxP == null || maxP.equals("")){
                JOptionPane.showMessageDialog(null, "Ingrese los datos correspondientes");
            }else{   
                int maxInsu = Integer.parseInt(maxI);
                int maxProd = Integer.parseInt(maxP);
                MasVendidos rep = new MasVendidos(null,true,maxInsu,maxProd);
                rep.setVisible(true);
            }
        
        }else if(ComprasTotales.isShowing()){
            if(diaIniCT.getSelectedItem().toString().equals("Dia") || 
                    mesIniCT.getSelectedItem().toString().equals("Mes") ||
                    anioIniCT.getSelectedItem().toString().equals("Anio") ||
                    diaFinCT.getSelectedItem().toString().equals("Dia") ||
                    mesFinCT.getSelectedItem().toString().equals("Mes") ||
                    anioFinCT.getSelectedItem().toString().equals("Anio") ){
                JOptionPane.showMessageDialog(null, "Seleccione una fecha correcta");
                
            }else{
                int rows[] = listaProveedoresCT.getSelectedRows();
                ArrayList<String> proveedores = new ArrayList<String>();
                ArrayList<String> rucs = new ArrayList<String>();
                for(int i = 0; i<rows.length;i++){
                    proveedores.add(listaProveedoresCT.getValueAt(rows[i], 0).toString());
                    rucs.add(listaProveedoresCT.getValueAt(rows[i], 1).toString());
                }
                ComprasTotales rep = new ComprasTotales(null,true,proveedores,rucs);
                rep.setVisible(true);
                
            }
            
            
        }else if(VentasTotales.isShowing()){
            if(diaIniVT.getSelectedItem().toString().equals("Dia") || 
                    mesIniVT.getSelectedItem().toString().equals("Mes") ||
                    anioIniVT.getSelectedItem().toString().equals("Anio") ||
                    diaFinVT.getSelectedItem().toString().equals("Dia") ||
                    mesFinVT.getSelectedItem().toString().equals("Mes") ||
                    anioFinVT.getSelectedItem().toString().equals("Anio") ){
                JOptionPane.showMessageDialog(null, "Seleccione una fecha correcta");
                
            }else{
                int rows[] = listaClientesVT.getSelectedRows();
                ArrayList<String> nombres = new ArrayList<String>();
                for(int i = 0; i<rows.length;i++){
                    nombres.add(listaClientesVT.getValueAt(rows[i], 0).toString());
                }
                VentasTotales rep = new VentasTotales(null,true,nombres);
                rep.setVisible(true);                
            }
            
            
        }else if(ReporteContable.isShowing()){
            if(diaIniRC.getSelectedItem().toString().equals("Dia") || 
                    mesIniRC.getSelectedItem().toString().equals("Mes") ||
                    anioIniRC.getSelectedItem().toString().equals("Anio") ||
                    diaFinRC.getSelectedItem().toString().equals("Dia") ||
                    mesFinRC.getSelectedItem().toString().equals("Mes") ||
                    anioFinRC.getSelectedItem().toString().equals("Anio") ){
                JOptionPane.showMessageDialog(null, "Seleccione una fecha correcta");
                
            }else{
                int rows[] = listaInsumosRC.getSelectedRows();
                ArrayList<String> nombresI = new ArrayList<String>();
                for(int i = 0; i<rows.length;i++){
                    nombresI.add(listaInsumosRC.getValueAt(rows[i], 0).toString());
                }
                int rows2[] = listaProductosRC.getSelectedRows();
                ArrayList<String> nombresP = new ArrayList<String>();
                for(int i = 0; i<rows2.length;i++){
                    nombresP.add(listaProductosRC.getValueAt(rows[i], 0).toString());
                }
                
                ReporteContable rep = new ReporteContable(null,true,nombresI,nombresP);
                rep.setVisible(true); 
                
            }
            
            
        }
    }//GEN-LAST:event_MostrarReporteActionPerformed

    private void diaIniCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaIniCTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaIniCTActionPerformed

    private void diaIniRCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaIniRCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaIniRCActionPerformed

    private void ExportarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportarReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExportarReporteActionPerformed

    private void MostrarReporteActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarReporteActionPerformed1
        
    }//GEN-LAST:event_MostrarReporteActionPerformed1

    private void mesIniVTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesIniVTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesIniVTActionPerformed

    private void diaIniVTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaIniVTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaIniVTActionPerformed

    private void atrasARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasARActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_atrasARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministracionDeReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministracionDeReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministracionDeReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministracionDeReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try{
                    new AdministracionDeReportes().setVisible(true);
                }
                catch (Exception ex){
                    System.out.println("Excepcion");
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ComprasTotales;
    private javax.swing.JButton ExportarReporte;
    private javax.swing.JPanel MasVendidos;
    private javax.swing.JPanel MejoresClientes;
    private javax.swing.JButton MostrarReporte;
    private javax.swing.JPanel ReporteContable;
    private javax.swing.JPanel VentasTotales;
    private javax.swing.JComboBox<String> anioFinCT;
    private javax.swing.JComboBox<String> anioFinRC;
    private javax.swing.JComboBox<String> anioFinVT;
    private javax.swing.JComboBox<String> anioIniCT;
    private javax.swing.JComboBox<String> anioIniRC;
    private javax.swing.JComboBox<String> anioIniVT;
    private javax.swing.JButton atrasAR;
    private javax.swing.JComboBox<String> diaFinCT;
    private javax.swing.JComboBox<String> diaFinRC;
    private javax.swing.JComboBox<String> diaFinVT;
    private javax.swing.JComboBox<String> diaIniCT;
    private javax.swing.JComboBox<String> diaIniRC;
    private javax.swing.JComboBox<String> diaIniVT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable listaClientesVT;
    private javax.swing.JTable listaInsumosRC;
    private javax.swing.JTable listaProductosRC;
    private javax.swing.JTable listaProveedoresCT;
    private javax.swing.JTextField maxClientes;
    private javax.swing.JTextField maxInsumos;
    private javax.swing.JTextField maxProductos;
    private javax.swing.JComboBox<String> mesFinCT;
    private javax.swing.JComboBox<String> mesFinRC;
    private javax.swing.JComboBox<String> mesFinVT;
    private javax.swing.JComboBox<String> mesIniCT;
    private javax.swing.JComboBox<String> mesIniRC;
    private javax.swing.JComboBox<String> mesIniVT;
    // End of variables declaration//GEN-END:variables
}
