/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controlador.*;
import Modelo.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author alulab14
 */
public class GestionReportes extends javax.swing.JFrame {

    /**
     * Creates new form GestionReportes
     */
    private PersonaNatural naturalSeleccionado;
    private PersonaJuridica juridicaSeleccionado;
    private Proveedor proveedorSeleccionado;
    private ReportesBL logicaN;

    public GestionReportes() {

        proveedorSeleccionado = new Proveedor();
        naturalSeleccionado = null;
        juridicaSeleccionado = null;
        logicaN = new ReportesBL();
        initComponents();
        limpiarCampos2();
        Excel icon = new Excel();
        icon.setVisible(true);
        icon.setSize(100, 100);
        Excel icon1 = new Excel();
        icon1.setVisible(true);
        icon1.setSize(100, 100);
        imagen.add(icon);
        imagen1.add(icon1);
        Explicacion.setText("<html> Seleccione esta opción para generar un informe de los clientes, <br> listados por monto total de pedidos </html>");
        Explicacion2.setText("<html> Seleccione esta opción para generar un informe de los productos más vendidos e insumos más comprados </html>");
        Explicacion3.setText("<html> Seleccione un proveedor y haga click en el botón Exportar para generar un informe de todos los insumos comprados a ese proveedor </html>");
        Explicacion4.setText("<html> Seleccione un cliente y haga click en el botón Exportar para generar un informe de todos los pedidos realizados por este cliente </html>");

    }

    public void limpiarCampos2() {
        naturalSeleccionado = null;
        juridicaSeleccionado = null;

        //Campos de Compras Totales
        TxtRazonSocial.setEnabled(false);
        TxtNombre.setEnabled(false);
        TxtRUC.setEnabled(false);
        TxtTelefono.setEnabled(false);
        TxtEmail.setEnabled(false);
        TxtRazonSocial.setText("");
        TxtNombre.setText("");
        TxtRUC.setText("");
        TxtTelefono.setText("");
        TxtEmail.setText("");

        //Campos de Ventas Totales
        TxtNombre1.setEnabled(false);
        TxtDocumento.setEnabled(false);
        TxtTelefono1.setEnabled(false);
        TxtEmail1.setEnabled(false);
        TxtNombre1.setText("");
        TxtDocumento.setText("");
        TxtTelefono1.setText("");
        TxtEmail1.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelesReportes = new javax.swing.JTabbedPane();
        mejoresClientes = new javax.swing.JPanel();
        btnExportar2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Explicacion = new javax.swing.JLabel();
        imagen = new javax.swing.JPanel();
        masVendidos = new javax.swing.JPanel();
        btnExportar3 = new javax.swing.JButton();
        Explicacion2 = new javax.swing.JLabel();
        imagen1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        comprasTotales = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        selProveedor = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        TxtRazonSocial = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtRUC = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TxtEmail = new javax.swing.JTextField();
        TxtNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnExportar = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        Explicacion3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ventasTotales = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        selCliente = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        TxtTelefono1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TxtDocumento = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        TxtEmail1 = new javax.swing.JTextField();
        TxtNombre1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnExportar1 = new javax.swing.JButton();
        cmbTipoCliente = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        Explicacion4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 500));
        setSize(new java.awt.Dimension(500, 600));

        panelesReportes.setMaximumSize(new java.awt.Dimension(500, 500));

        btnExportar2.setText("Exportar");
        btnExportar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExportar2MouseClicked(evt);
            }
        });
        btnExportar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportar2ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reporte de Mejores Clientes:");

        Explicacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout imagenLayout = new javax.swing.GroupLayout(imagen);
        imagen.setLayout(imagenLayout);
        imagenLayout.setHorizontalGroup(
            imagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );
        imagenLayout.setVerticalGroup(
            imagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 133, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mejoresClientesLayout = new javax.swing.GroupLayout(mejoresClientes);
        mejoresClientes.setLayout(mejoresClientesLayout);
        mejoresClientesLayout.setHorizontalGroup(
            mejoresClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mejoresClientesLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(Explicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(mejoresClientesLayout.createSequentialGroup()
                .addGroup(mejoresClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mejoresClientesLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mejoresClientesLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(mejoresClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExportar2)
                            .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mejoresClientesLayout.setVerticalGroup(
            mejoresClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mejoresClientesLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(Explicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnExportar2)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        panelesReportes.addTab("Mejores Clientes", mejoresClientes);

        btnExportar3.setText("Exportar");
        btnExportar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExportar3MouseClicked(evt);
            }
        });
        btnExportar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout imagen1Layout = new javax.swing.GroupLayout(imagen1);
        imagen1.setLayout(imagen1Layout);
        imagen1Layout.setHorizontalGroup(
            imagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );
        imagen1Layout.setVerticalGroup(
            imagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 133, Short.MAX_VALUE)
        );

        jLabel2.setText("Reporte de Productos e Insumos:");

        javax.swing.GroupLayout masVendidosLayout = new javax.swing.GroupLayout(masVendidos);
        masVendidos.setLayout(masVendidosLayout);
        masVendidosLayout.setHorizontalGroup(
            masVendidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, masVendidosLayout.createSequentialGroup()
                .addGap(0, 66, Short.MAX_VALUE)
                .addComponent(Explicacion2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(masVendidosLayout.createSequentialGroup()
                .addGroup(masVendidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(masVendidosLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(masVendidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(imagen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(masVendidosLayout.createSequentialGroup()
                                .addComponent(btnExportar3)
                                .addGap(75, 75, 75))))
                    .addGroup(masVendidosLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        masVendidosLayout.setVerticalGroup(
            masVendidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masVendidosLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(Explicacion2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(imagen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnExportar3)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        panelesReportes.addTab("Mas Vendidos", masVendidos);

        jLabel3.setText("Lista de Proveedores:");

        selProveedor.setText("Seleccionar Proveedor");
        selProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selProveedorActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Información del Proveedor:"));

        jLabel4.setText("Razón Social:");

        TxtRazonSocial.setText("jTextField1");

        jLabel5.setText("R.U.C. :");

        TxtRUC.setText("jTextField3");
        TxtRUC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtRUCKeyTyped(evt);
            }
        });

        jLabel7.setText("Teléfono:");

        TxtTelefono.setText("jTextField5");
        TxtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtTelefonoKeyTyped(evt);
            }
        });

        jLabel8.setText("Email:");

        TxtEmail.setText("jTextField6");
        TxtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtEmailKeyTyped(evt);
            }
        });

        TxtNombre.setText("jTextField2");

        jLabel6.setText("Nombre:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TxtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8))
                                    .addGap(48, 48, 48)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TxtRUC, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(63, 63, 63))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TxtRUC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        btnExportar.setText("Exportar");
        btnExportar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExportarMouseClicked(evt);
            }
        });

        jLabel18.setText("Aca falta algo no se que, relacionado a seleccionar fechas y cliente");

        Explicacion3.setText("Aca falta algo no se que, relacionado a seleccionar fechas y proveedor");

        jLabel9.setText("Reporte de Compras por Proveedor:");

        javax.swing.GroupLayout comprasTotalesLayout = new javax.swing.GroupLayout(comprasTotales);
        comprasTotales.setLayout(comprasTotalesLayout);
        comprasTotalesLayout.setHorizontalGroup(
            comprasTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comprasTotalesLayout.createSequentialGroup()
                .addGroup(comprasTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(comprasTotalesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(comprasTotalesLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(btnExportar))
                    .addGroup(comprasTotalesLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(comprasTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(comprasTotalesLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(selProveedor))
                            .addComponent(Explicacion3, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(comprasTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(comprasTotalesLayout.createSequentialGroup()
                    .addGap(66, 66, 66)
                    .addComponent(jLabel18)
                    .addContainerGap(51, Short.MAX_VALUE)))
        );
        comprasTotalesLayout.setVerticalGroup(
            comprasTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, comprasTotalesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Explicacion3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(comprasTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(selProveedor))
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnExportar)
                .addContainerGap())
            .addGroup(comprasTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(comprasTotalesLayout.createSequentialGroup()
                    .addGap(241, 241, 241)
                    .addComponent(jLabel18)
                    .addContainerGap(233, Short.MAX_VALUE)))
        );

        panelesReportes.addTab("Compras Totales", comprasTotales);

        jLabel11.setText("Lista de Clientes:");

        selCliente.setText("Seleccionar Cliente");
        selCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selClienteActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Información del Cliente:"));

        jLabel13.setText("Documento");

        TxtTelefono1.setText("jTextField3");
        TxtTelefono1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtTelefono1KeyTyped(evt);
            }
        });

        jLabel14.setText("Teléfono:");

        TxtDocumento.setText("jTextField5");
        TxtDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtDocumentoKeyTyped(evt);
            }
        });

        jLabel15.setText("Email:");

        TxtEmail1.setText("jTextField6");
        TxtEmail1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtEmail1KeyTyped(evt);
            }
        });

        TxtNombre1.setText("jTextField2");

        jLabel16.setText("Nombre:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtEmail1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                                    .addComponent(TxtTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtDocumento))))))
                .addGap(63, 63, 63))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(TxtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(TxtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(TxtTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(TxtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        btnExportar1.setText("Exportar");
        btnExportar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExportar1MouseClicked(evt);
            }
        });

        cmbTipoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Natural", "Juridico" }));
        cmbTipoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoClienteActionPerformed(evt);
            }
        });

        jLabel17.setText("Tipo de Cliente:");

        Explicacion4.setText("Aca falta algo no se que, relacionado a seleccionar fechas y cliente");

        jLabel10.setText("Reporte de Pedidos por Cliente:");

        javax.swing.GroupLayout ventasTotalesLayout = new javax.swing.GroupLayout(ventasTotales);
        ventasTotales.setLayout(ventasTotalesLayout);
        ventasTotalesLayout.setHorizontalGroup(
            ventasTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventasTotalesLayout.createSequentialGroup()
                .addGroup(ventasTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventasTotalesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ventasTotalesLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(btnExportar1))
                    .addGroup(ventasTotalesLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(ventasTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ventasTotalesLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(105, 105, 105)
                                .addComponent(cmbTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ventasTotalesLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(selCliente)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventasTotalesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(ventasTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(Explicacion4, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        ventasTotalesLayout.setVerticalGroup(
            ventasTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventasTotalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(Explicacion4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ventasTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(ventasTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(selCliente))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExportar1)
                .addContainerGap())
        );

        panelesReportes.addTab("VentasTotales", ventasTotales);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelesReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelesReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtEmailKeyTyped
        String texto = TxtEmail.getText();
        Pattern EMAIL_VALIDO = Pattern.compile("^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{1,6}$", Pattern.CASE_INSENSITIVE);
        Matcher matcher = EMAIL_VALIDO.matcher(texto);
        if (!matcher.find()) {
            TxtEmail.setForeground(java.awt.Color.RED);
        } else {
            TxtEmail.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_TxtEmailKeyTyped

    private void TxtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTelefonoKeyTyped
        String texto = TxtTelefono.getText();
        Pattern EMAIL_VALIDO = Pattern.compile("^[0-9]{6}$", Pattern.CASE_INSENSITIVE);
        Matcher matcher = EMAIL_VALIDO.matcher(texto);
        if (!matcher.find()) {
            TxtTelefono.setForeground(java.awt.Color.RED);
        } else {
            TxtTelefono.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_TxtTelefonoKeyTyped

    private void TxtRUCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtRUCKeyTyped
        String texto = TxtRUC.getText();
        Pattern EMAIL_VALIDO = Pattern.compile("^[0-9]{10}$", Pattern.CASE_INSENSITIVE);
        Matcher matcher = EMAIL_VALIDO.matcher(texto);
        if (!matcher.find()) {
            TxtRUC.setForeground(java.awt.Color.RED);
        } else {
            TxtRUC.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_TxtRUCKeyTyped

    private void selProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selProveedorActionPerformed
        // TODO add your handling code here:
        BuscarProveedor frm = new BuscarProveedor(null, true);
        frm.setVisible(true);
        proveedorSeleccionado = frm.getProveedorSeleccionado();
        if (proveedorSeleccionado != null) {
            TxtRazonSocial.setText(proveedorSeleccionado.getRazonSocial());
            TxtNombre.setText(proveedorSeleccionado.getNombre());
            TxtRUC.setText(proveedorSeleccionado.getRUC());
            TxtTelefono.setText(proveedorSeleccionado.getTelefono());
            TxtEmail.setText(proveedorSeleccionado.getEmail());

        }
    }//GEN-LAST:event_selProveedorActionPerformed

    private void selClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selClienteActionPerformed
        // TODO add your handling code here:
        limpiarCampos2();
        String tipoCliente = cmbTipoCliente.getSelectedItem().toString();
        if (tipoCliente != null) {
            if (tipoCliente.equals("Natural")) {
                juridicaSeleccionado = null;
                BuscarClienteNatural frm = new BuscarClienteNatural(null, true);
                frm.setVisible(true);
                naturalSeleccionado = frm.getSeleccionado();
                if (naturalSeleccionado != null) {
                    TxtNombre1.setText(naturalSeleccionado.getNombre() + " " + naturalSeleccionado.getApellidoP() + " " + naturalSeleccionado.getApellidoM());
                    TxtDocumento.setText("DNI: " + naturalSeleccionado.getDNI());
                    TxtTelefono1.setText(naturalSeleccionado.getTelefono());
                    TxtEmail1.setText(naturalSeleccionado.getEmail());
                }
            } else if (tipoCliente.equals("Juridico")) {
                naturalSeleccionado = null;
                BuscarClienteJuridico frm = new BuscarClienteJuridico(null, true);
                frm.setVisible(true);
                juridicaSeleccionado = frm.getSeleccionado();
                if (juridicaSeleccionado != null) {
                    TxtNombre1.setText(juridicaSeleccionado.getNombre());
                    TxtDocumento.setText("R.U.C.: " + juridicaSeleccionado.getRUC());
                    TxtTelefono1.setText(juridicaSeleccionado.getTelefono());
                    TxtEmail1.setText(juridicaSeleccionado.getEmail());
                }
            }
        }
    }//GEN-LAST:event_selClienteActionPerformed

    private void TxtTelefono1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTelefono1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTelefono1KeyTyped

    private void TxtDocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDocumentoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDocumentoKeyTyped

    private void TxtEmail1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtEmail1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEmail1KeyTyped

    private void cmbTipoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoClienteActionPerformed

    private void btnExportarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportarMouseClicked
        // TODO add your handling code here:
        try {
            int cod = logicaN.reporteComprasTotales(proveedorSeleccionado);
            if (cod == 1) {
                JOptionPane.showMessageDialog(null, "Se creo correctamente");
            } else {
                JOptionPane.showMessageDialog(null, "Problemas al crear el archivo");
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_btnExportarMouseClicked

    private void btnExportar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportar1MouseClicked
        // TODO add your handling code here:
        try {
            int cod = logicaN.reporteVentasTotales(naturalSeleccionado, juridicaSeleccionado);
            if (cod == 1) {
                JOptionPane.showMessageDialog(null, "Se creo correctamente");
            } else {
                JOptionPane.showMessageDialog(null, "Problemas al crear el archivo");
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnExportar1MouseClicked

    private void btnExportar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportar2MouseClicked
        // TODO add your handling code here:
        try {
            int cod = logicaN.reporteClientes();
            if (cod == 1) {
                JOptionPane.showMessageDialog(null, "Se creo correctamente");
            } else {
                JOptionPane.showMessageDialog(null, "Problemas al crear el archivo");
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnExportar2MouseClicked

    private void btnExportar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportar2ActionPerformed

    private void btnExportar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportar3MouseClicked
        // TODO add your handling code here:
        try {
            int cod = logicaN.reporteProductosEInsumos();
            if (cod == 1) {
                JOptionPane.showMessageDialog(null, "Se creo correctamente");
            } else {
                JOptionPane.showMessageDialog(null, "Problemas al crear el archivo");
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnExportar3MouseClicked

    private void btnExportar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportar3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionReportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Explicacion;
    private javax.swing.JLabel Explicacion2;
    private javax.swing.JLabel Explicacion3;
    private javax.swing.JLabel Explicacion4;
    private javax.swing.JTextField TxtDocumento;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtEmail1;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtNombre1;
    private javax.swing.JTextField TxtRUC;
    private javax.swing.JTextField TxtRazonSocial;
    private javax.swing.JTextField TxtTelefono;
    private javax.swing.JTextField TxtTelefono1;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnExportar1;
    private javax.swing.JButton btnExportar2;
    private javax.swing.JButton btnExportar3;
    private javax.swing.JComboBox<String> cmbTipoCliente;
    private javax.swing.JPanel comprasTotales;
    private javax.swing.JPanel imagen;
    private javax.swing.JPanel imagen1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel masVendidos;
    private javax.swing.JPanel mejoresClientes;
    private javax.swing.JTabbedPane panelesReportes;
    private javax.swing.JButton selCliente;
    private javax.swing.JButton selProveedor;
    private javax.swing.JPanel ventasTotales;
    // End of variables declaration//GEN-END:variables
}
