/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.Insumo;
import Modelo.Proveedor;
import Controlador.InsumoBL;
import Controlador.ProductoBL;
import Modelo.TipoProductoG;
import Modelo.UnidadDeMedida;
import Vistas.BuscarProveedor;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Pablo
 */

public class GestionInsumo extends javax.swing.JFrame {
    private InsumoBL logicaNegocioInsumo;
    private ProductoBL LogicaNegocio;
    private Proveedor proveedorSeleccionado;
    
    public void estado(String estado){
        switch(estado){
            case "inicial":
                JMNuevo.setEnabled(true);
                JMEliminar.setEnabled(false); JMEliminar.setForeground(Color.gray);
                JMModificar.setEnabled(false); JMModificar.setForeground(Color.gray);
                JMCancelar.setEnabled(false); JMCancelar.setForeground(Color.gray);
                JMGuardar.setEnabled(false); JMGuardar.setForeground(Color.gray);
                JMBuscar.setEnabled(true);
                txtIdInsumo.setEnabled(false); txtIdInsumo.setBackground(Color.lightGray);
                txtNombreInsumo.setEnabled(false); txtNombreInsumo.setBackground(Color.lightGray);
                txtColor.setEnabled(false); txtColor.setBackground(Color.lightGray);
                txtDescripcion.setEnabled(false); txtDescripcion.setBackground(Color.lightGray);
                txtStockMinimo.setEnabled(false); txtStockMinimo.setBackground(Color.lightGray);
                cboTipo.setEnabled(false);
                cboUnidadMedida.setEnabled(false);
                btnBuscarProveedor.setEnabled(false);
                txtIdProveedor.setEnabled(false); txtIdProveedor.setBackground(Color.lightGray);
                txtNombreProveedor.setEnabled(false); txtNombreProveedor.setBackground(Color.lightGray);
                txtPrecio.setEnabled(false); txtPrecio.setBackground(Color.lightGray);
                break;
            case "nuevo":
                JMNuevo.setEnabled(true); JMNuevo.setForeground(Color.black);
                JMCancelar.setEnabled(true); JMCancelar.setForeground(Color.black);
                JMGuardar.setEnabled(true); JMGuardar.setForeground(Color.black);
                JMEliminar.setEnabled(false); JMEliminar.setForeground(Color.gray);
                JMModificar.setEnabled(false); JMModificar.setForeground(Color.gray);
                txtIdInsumo.setEnabled(true); txtIdInsumo.setBackground(Color.gray);
                txtNombreInsumo.setEnabled(true); txtNombreInsumo.setBackground(Color.white);
                txtColor.setEnabled(true); txtColor.setBackground(Color.white);
                txtDescripcion.setEnabled(true); txtDescripcion.setBackground(Color.white);
                txtStockMinimo.setEnabled(true); txtStockMinimo.setBackground(Color.white);
                cboTipo.setEnabled(true);
                cboUnidadMedida.setEnabled(true);
                btnBuscarProveedor.setEnabled(true);
                txtIdProveedor.setEnabled(false); 
                txtNombreProveedor.setEnabled(false); 
                txtPrecio.setEnabled(true); txtPrecio.setBackground(Color.white);
                break;
        }
    }

    public void cargarCboUnidadMedidad(){
        ArrayList<TipoProductoG> listaProd = LogicaNegocio.listarTipoProducto();
                for (TipoProductoG tp : listaProd) {
                    cboTipo.addItem(tp);
                }
        ArrayList<UnidadDeMedida> listaUn = LogicaNegocio.listarUnidades();
                for (UnidadDeMedida u : listaUn) {
                    cboUnidadMedida.addItem(u);
                }
    }
    

    
    public GestionInsumo() {
        initComponents();
        logicaNegocioInsumo = new InsumoBL();
        LogicaNegocio = new ProductoBL();
        estado("inicial");
        
        cargarCboUnidadMedidad();
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdInsumo = new javax.swing.JTextField();
        txtNombreInsumo = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        cboTipo = new javax.swing.JComboBox();
        cboUnidadMedida = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtStockMinimo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNombreProveedor = new javax.swing.JTextField();
        txtIdProveedor = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnBuscarProveedor = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMNuevo = new javax.swing.JMenu();
        JMGuardar = new javax.swing.JMenu();
        JMBuscar = new javax.swing.JMenu();
        JMModificar = new javax.swing.JMenu();
        JMEliminar = new javax.swing.JMenu();
        JMCancelar = new javax.swing.JMenu();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Datos Generales"));

        jLabel2.setText("Id Insumo:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Color:");

        jLabel5.setText("Tipo de Producto:");

        jLabel6.setText("Unidad de Medida:");

        jLabel7.setText("Descripción:");

        jLabel11.setText("Stock Minimo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboUnidadMedida, 0, 132, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStockMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombreInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtStockMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Datos del Proveedor"));

        jLabel9.setText("Nombre:");

        jLabel8.setText("Id Proveedor");

        jLabel10.setText("Precio:");

        btnBuscarProveedor.setText("...");
        btnBuscarProveedor.setEnabled(false);
        btnBuscarProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarProveedorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtIdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtIdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProveedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        JMNuevo.setText("Nuevo");
        JMNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMNuevoMouseClicked(evt);
            }
        });
        jMenuBar1.add(JMNuevo);

        JMGuardar.setText("Guardar");
        JMGuardar.setEnabled(false);
        JMGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMGuardarMouseClicked(evt);
            }
        });
        jMenuBar1.add(JMGuardar);

        JMBuscar.setText("Buscar");
        JMBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMBuscarMouseClicked(evt);
            }
        });
        jMenuBar1.add(JMBuscar);

        JMModificar.setText("Modificar");
        jMenuBar1.add(JMModificar);

        JMEliminar.setText("Eliminar");
        jMenuBar1.add(JMEliminar);

        JMCancelar.setText("Cancelar");
        jMenuBar1.add(JMCancelar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMNuevoMouseClicked
        // TODO add your handling code here:
        estado("nuevo");
    }//GEN-LAST:event_JMNuevoMouseClicked

    private void JMGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMGuardarMouseClicked
        try {
            // TODO add your handling code here:
            
            Insumo i = new Insumo();
            i.setNombre(txtNombreInsumo.getText());
            i.setDescripcion(txtDescripcion.getText());
            i.setColor(txtColor.getText());
            i.setStockMinimo(Integer.valueOf(txtStockMinimo.getText()));
            double precio = Double.valueOf(txtPrecio.getText());
            int id = logicaNegocioInsumo.registrarInsumo(i, proveedorSeleccionado, precio);
            txtDescripcion.setText(String.valueOf(id));
            estado("guardar");
            
        } catch (SQLException ex) {
            Logger.getLogger(GestionInsumo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_JMGuardarMouseClicked

    private void btnBuscarProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarProveedorMouseClicked
        // TODO add your handling code here:
        BuscarProveedor frmBP = new BuscarProveedor(null,true);
        frmBP.setVisible(true);
        
        proveedorSeleccionado = frmBP.getProveedorSeleccionado();
        if(proveedorSeleccionado != null){
            txtIdProveedor.setText(proveedorSeleccionado.getIDProveedor());
            txtNombreProveedor.setText(proveedorSeleccionado.getNombre());
        }
    }//GEN-LAST:event_btnBuscarProveedorMouseClicked

    private void JMBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMBuscarMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JMBuscarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionInsumo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMBuscar;
    private javax.swing.JMenu JMCancelar;
    private javax.swing.JMenu JMEliminar;
    private javax.swing.JMenu JMGuardar;
    private javax.swing.JMenu JMModificar;
    private javax.swing.JMenu JMNuevo;
    private javax.swing.JButton btnBuscarProveedor;
    private javax.swing.JComboBox cboTipo;
    private javax.swing.JComboBox cboUnidadMedida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtIdInsumo;
    private javax.swing.JTextField txtIdProveedor;
    private javax.swing.JTextField txtNombreInsumo;
    private javax.swing.JTextField txtNombreProveedor;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStockMinimo;
    // End of variables declaration//GEN-END:variables
}
