/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import Modelo.MejorCliente;

/**
 *
 * @author Kenny-pc
 */
public class MejoresClientes extends java.awt.Dialog {

    /**
     * Creates new form Reporte
     */
    public MejoresClientes(java.awt.Frame parent, boolean modal,int numDatos) {
        super(parent, modal);
        initComponents();
        
        
        ArrayList<MejorCliente> listClientes = new ArrayList<MejorCliente>();
                
        MejorCliente c1 = new MejorCliente("Juan Perez",  new Float(362.23), "18/01/2018");
        MejorCliente c2 = new MejorCliente("Yuri Gomez",  new Float(300.1), "20/03/2018");
        MejorCliente c3 = new MejorCliente("Rocio Quiroz",  new Float(222.22), "15/02/2018");
        MejorCliente c4 = new MejorCliente("Paulo Quiroga",  new Float(152.36), "31/12/2017");
        listClientes.add(c1);
        listClientes.add(c2);
        listClientes.add(c3);
        listClientes.add(c4);
                
        DefaultTableModel modelo = (DefaultTableModel) tablaMC.getModel();
        Object[] fila = new Object[3];
        for(int i=0; (i<numDatos)&&(i<listClientes.size());i++){
            fila[0] = listClientes.get(i).getName();
            fila[1] = listClientes.get(i).getMontoTotal();
            fila[2] = listClientes.get(i).getFechaUltEnt();
            modelo.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMC = new javax.swing.JTable();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        tablaMC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Cliente", "Monto Total", "Fecha Ult Compra"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaMC);

        jPanel1.add(jScrollPane1);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MejoresClientes dialog = new MejoresClientes(new java.awt.Frame(), true,1);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaMC;
    // End of variables declaration//GEN-END:variables
}
