//   private void jButton2ActionPerformed(java.awt.event.ActionEvent evt){
//    // First we define float variables.
//    float num1, num2, result;
//    // We have to parse the text to a type float.
//    num1 = Float.parseFloat(jTextField1.getText());
//    num2 = Float.parseFloat(jTextField2.getText());
//    // Now we can perform the addition.
//    result = num1+num2;
//    // We will now pass the value of result to jTextField3.
//    // At the same time, we are going to 
//    // change the value of result from a float to a string.
//    jTextField3.setText(String.valueOf(result));
//}
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//#########################################################################################
package Vistas;

import Modelo.Persona;
import Modelo.Proveedor;
import javax.swing.JOptionPane;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alulab14
 */
public class ProveedoresUI extends javax.swing.JFrame {
    int seleccionado;
    ArrayList<Proveedor> listaProveedores;

    /**
     * Creates new form ProveedoresUI
     */
    public ProveedoresUI() {
        initComponents();
        //Creando la lista de empleados
        listaProveedores = new ArrayList<Proveedor>();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextoNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TextoTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TextoMail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TextoRUC = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TextoNombreRep = new javax.swing.JTextField();
        TextoApPRep = new javax.swing.JTextField();
        TextoApMRep = new javax.swing.JTextField();
        TextoDNIRep = new javax.swing.JTextField();
        TextoTelefonoRep = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        BCancelar = new javax.swing.JButton();
        BRegistrar = new javax.swing.JButton();
        BModificar = new javax.swing.JButton();
        BEliminar = new javax.swing.JButton();
        BBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProveedores = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestionar Proveedores"));

        jLabel1.setText("Datos del proveedor:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Teléfono:");

        jLabel6.setText("Correo electrónico:");

        jLabel7.setText("R.U.C. :");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Representante"));

        jLabel8.setText("Nombre del Representante:");

        jLabel9.setText("Apellido Paterno del Representante:");

        jLabel10.setText("Apellido Materno del Representante:");

        jLabel11.setText("D.N.I. del Representante:");

        jLabel12.setText("Teléfono del Representante:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextoNombreRep)
                            .addComponent(TextoApPRep)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextoApMRep, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                            .addComponent(TextoDNIRep)
                            .addComponent(TextoTelefonoRep))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TextoNombreRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TextoApPRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TextoApMRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(TextoDNIRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(TextoTelefonoRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setText("Datos del representante de este proveedor:");

        BCancelar.setText("Terminar");
        BCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancelarActionPerformed(evt);
            }
        });

        BRegistrar.setText("Registrar Nuevo");
        BRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRegistrarActionPerformed(evt);
            }
        });

        BModificar.setText("Modificar ");
        BModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BModificarActionPerformed(evt);
            }
        });

        BEliminar.setText("Eliminar ");
        BEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEliminarActionPerformed(evt);
            }
        });

        BBuscar.setText("Ver");
        BBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBuscarActionPerformed(evt);
            }
        });

        TablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "R.U.C.", "Nombre", "Nombre Representante", "Apellido Representante", "Teléfono Representante"
            }
        ));
        jScrollPane1.setViewportView(TablaProveedores);

        jButton1.setText("Guardar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(BCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextoNombre)
                                    .addComponent(TextoTelefono)
                                    .addComponent(TextoMail, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                    .addComponent(TextoRUC)))
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(46, 46, 46))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel4)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(TextoRUC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BRegistrar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(TextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(TextoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BModificar))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(TextoMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(BEliminar)))))
                .addComponent(jLabel5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(BBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(39, 39, 39)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BCancelar)
                .addGap(265, 265, 265))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_BCancelarActionPerformed

    private void BModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BModificarActionPerformed

        try {
            //new test.ModificarProveedor(listaProveedores).setVisible(true);
            int index = seleccionado;
            Proveedor ProveedorSeleccionado = listaProveedores.get(index);
            //Cargar campos        

            ProveedorSeleccionado.setNombre(TextoNombre.getText());
            String ruc = TextoRUC.getText();
            try {
                int entero = Integer.parseInt(ruc);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "El R.U.C debe ser un número");
            }
            ProveedorSeleccionado.setRUC(TextoRUC.getText());
            String telefono = TextoTelefono.getText();
            try {
                int entero = Integer.parseInt(telefono);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "El teléfono debe ser un número");
            }
            ProveedorSeleccionado.setTelefono(TextoTelefono.getText());
            ProveedorSeleccionado.setCorreo(TextoMail.getText());
            ProveedorSeleccionado.getRepresentante().setNombres(TextoNombreRep.getText());
            ProveedorSeleccionado.getRepresentante().setApellidoP(TextoApPRep.getText());
            ProveedorSeleccionado.getRepresentante().setApellidoM(TextoApMRep.getText());
            ProveedorSeleccionado.getRepresentante().setDNI(TextoDNIRep.getText());
            ProveedorSeleccionado.getRepresentante().setTelefono(TextoTelefonoRep.getText());
            DefaultTableModel modelo = (DefaultTableModel) TablaProveedores.getModel();
            modelo.setRowCount(0);
            Object[] fila = new Object[5];
            for (int i = 0; i < listaProveedores.size(); i++) {
                fila[0] = listaProveedores.get(i).getRUC();
                fila[1] = listaProveedores.get(i).getNombre();
                fila[2] = listaProveedores.get(i).getRepresentante().getNombres();
                fila[3] = listaProveedores.get(i).getRepresentante().getApellidoP();
                fila[4] = listaProveedores.get(i).getRepresentante().getTelefono();
                modelo.addRow(fila);
            }
            

        } catch (Exception ex) {
            Logger.getLogger(ProveedoresUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BModificarActionPerformed

    private void BRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRegistrarActionPerformed
        String ruc = TextoRUC.getText();
        try {
            int entero = Integer.parseInt(ruc);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "El R.U.C debe ser un número");
            return;
        }
        String nombre = TextoNombre.getText();
        String telefono = TextoTelefono.getText();
        try {
            int entero = Integer.parseInt(telefono);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "El teléfono debe ser un número");
            return;
        }
        String correo = TextoMail.getText();
        String nomrep = TextoNombreRep.getText();
        String apprep = TextoApPRep.getText();
        String apmrep = TextoApMRep.getText();
        String dnirep = TextoDNIRep.getText();
        String telrep = TextoTelefonoRep.getText();

        if (ruc == null || nombre == null || telefono == null || correo == null || nomrep == null || apprep == null || apmrep == null || dnirep == null || telrep == null) {
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos");
        }

        Persona rep = new Persona(nomrep, apprep, apmrep, dnirep, telrep);
        Proveedor prov = new Proveedor(ruc, nombre, rep, telefono, correo);
        listaProveedores.add(prov);

        DefaultTableModel modelo = (DefaultTableModel) TablaProveedores.getModel();
        modelo.setRowCount(0);
        Object[] fila = new Object[5];
        for (int i = 0; i < listaProveedores.size(); i++) {
            fila[0] = listaProveedores.get(i).getRUC();
            fila[1] = listaProveedores.get(i).getNombre();
            fila[2] = listaProveedores.get(i).getRepresentante().getNombres();
            fila[3] = listaProveedores.get(i).getRepresentante().getApellidoP();
            fila[4] = listaProveedores.get(i).getRepresentante().getTelefono();
            modelo.addRow(fila);
        }

    }//GEN-LAST:event_BRegistrarActionPerformed

    private void BEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEliminarActionPerformed
        try {
            int ind = TablaProveedores.getSelectedRow();

            int Bdialogo = JOptionPane.YES_NO_OPTION;
            int resultado = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea eliminar el proveedor?", "Atención", Bdialogo);
            if (resultado == JOptionPane.YES_OPTION) {
                listaProveedores.remove(ind);
                DefaultTableModel modelo = (DefaultTableModel) TablaProveedores.getModel();
                modelo.setRowCount(0);
                Object[] fila = new Object[5];
                for (int i = 0; i < listaProveedores.size(); i++) {
                    fila[0] = listaProveedores.get(i).getRUC();
                    fila[1] = listaProveedores.get(i).getNombre();
                    fila[2] = listaProveedores.get(i).getRepresentante().getNombres();
                    fila[3] = listaProveedores.get(i).getRepresentante().getApellidoP();
                    fila[4] = listaProveedores.get(i).getRepresentante().getTelefono();
                    modelo.addRow(fila);
                }
            }
            if (resultado == JOptionPane.NO_OPTION) {

            }

        } catch (Exception ex) {
            Logger.getLogger(ProveedoresUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BEliminarActionPerformed

    private void BBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBuscarActionPerformed
       
        seleccionado = TablaProveedores.getSelectedRow();
        Proveedor ProveedorSeleccionado = listaProveedores.get(seleccionado);
        TextoNombre.setText(ProveedorSeleccionado.getNombre());
        TextoRUC.setText(ProveedorSeleccionado.getRUC());
        TextoTelefono.setText(ProveedorSeleccionado.getTelefono());
        TextoMail.setText(ProveedorSeleccionado.getCorreo());
        TextoNombreRep.setText(ProveedorSeleccionado.getRepresentante().getNombres());
        TextoApPRep.setText(ProveedorSeleccionado.getRepresentante().getApellidoP());
        TextoApMRep.setText(ProveedorSeleccionado.getRepresentante().getApellidoM());
        TextoDNIRep.setText(ProveedorSeleccionado.getRepresentante().getDNI());
        TextoTelefonoRep.setText(ProveedorSeleccionado.getRepresentante().getTelefono());
    }//GEN-LAST:event_BBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProveedoresUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProveedoresUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProveedoresUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProveedoresUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ProveedoresUI().setVisible(true);
                } catch (Exception ex) {
                    System.out.println(ex.getMessage());
                }
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBuscar;
    private javax.swing.JButton BCancelar;
    private javax.swing.JButton BEliminar;
    private javax.swing.JButton BModificar;
    private javax.swing.JButton BRegistrar;
    private javax.swing.JTable TablaProveedores;
    private javax.swing.JTextField TextoApMRep;
    private javax.swing.JTextField TextoApPRep;
    private javax.swing.JTextField TextoDNIRep;
    private javax.swing.JTextField TextoMail;
    private javax.swing.JTextField TextoNombre;
    private javax.swing.JTextField TextoNombreRep;
    private javax.swing.JTextField TextoRUC;
    private javax.swing.JTextField TextoTelefono;
    private javax.swing.JTextField TextoTelefonoRep;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
