/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Katherine Espinoza 20122127
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     * @throws java.lang.Exception
     */
    public VentanaPrincipal() throws Exception{
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(750, 500);
        this.getContentPane().setBackground(Color.WHITE);
        Fondo fondo = new Fondo();
        fondo.setSize(750, 500);
        fondo.setVisible(true);
        FondoPanel.add(fondo);
        FondoPanel.setLocation(0, 25);
        FondoPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        minimizar = new javax.swing.JLabel();
        Cerrar = new javax.swing.JLabel();
        FondoPanel = new javax.swing.JPanel();
        InsumoBtn = new javax.swing.JPanel();
        txtInsumo = new javax.swing.JLabel();
        proveedorBtn = new javax.swing.JPanel();
        txtProveedor = new javax.swing.JLabel();
        reporteBtn = new javax.swing.JPanel();
        txtReporte = new javax.swing.JLabel();
        prodBtn = new javax.swing.JPanel();
        txtProducto = new javax.swing.JLabel();
        salirBtn = new javax.swing.JPanel();
        txtSalir = new javax.swing.JLabel();
        PedidoBtn = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JLabel();
        reporteBtn2 = new javax.swing.JPanel();
        txtReporte2 = new javax.swing.JLabel();
        usuBtn1 = new javax.swing.JPanel();
        txtUsuario1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Titulo.setBackground(new java.awt.Color(240, 52, 52));

        txtTitulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(255, 255, 255));
        txtTitulo.setText("Menú");

        minimizar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        minimizar.setForeground(new java.awt.Color(255, 255, 255));
        minimizar.setText("_");
        minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
        });

        Cerrar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Cerrar.setForeground(new java.awt.Color(255, 255, 255));
        Cerrar.setText("x");
        Cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout TituloLayout = new javax.swing.GroupLayout(Titulo);
        Titulo.setLayout(TituloLayout);
        TituloLayout.setHorizontalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 433, Short.MAX_VALUE)
                .addComponent(minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        TituloLayout.setVerticalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TituloLayout.createSequentialGroup()
                .addGroup(TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cerrar)
                    .addComponent(minimizar)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        FondoPanel.setPreferredSize(new java.awt.Dimension(114, 500));

        InsumoBtn.setBackground(new java.awt.Color(153, 153, 153));
        InsumoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InsumoBtnMouseClicked(evt);
            }
        });

        txtInsumo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtInsumo.setForeground(new java.awt.Color(255, 255, 255));
        txtInsumo.setText("Insumo");

        javax.swing.GroupLayout InsumoBtnLayout = new javax.swing.GroupLayout(InsumoBtn);
        InsumoBtn.setLayout(InsumoBtnLayout);
        InsumoBtnLayout.setHorizontalGroup(
            InsumoBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsumoBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtInsumo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InsumoBtnLayout.setVerticalGroup(
            InsumoBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InsumoBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtInsumo)
                .addContainerGap())
        );

        proveedorBtn.setBackground(new java.awt.Color(153, 153, 153));
        proveedorBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proveedorBtnMouseClicked(evt);
            }
        });

        txtProveedor.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtProveedor.setForeground(new java.awt.Color(255, 255, 255));
        txtProveedor.setText("Proveedor");

        javax.swing.GroupLayout proveedorBtnLayout = new javax.swing.GroupLayout(proveedorBtn);
        proveedorBtn.setLayout(proveedorBtnLayout);
        proveedorBtnLayout.setHorizontalGroup(
            proveedorBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(proveedorBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtProveedor)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        proveedorBtnLayout.setVerticalGroup(
            proveedorBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(proveedorBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtProveedor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        reporteBtn.setBackground(new java.awt.Color(153, 153, 153));
        reporteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reporteBtnMouseClicked(evt);
            }
        });

        txtReporte.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtReporte.setForeground(new java.awt.Color(255, 255, 255));
        txtReporte.setText("Reporte");

        javax.swing.GroupLayout reporteBtnLayout = new javax.swing.GroupLayout(reporteBtn);
        reporteBtn.setLayout(reporteBtnLayout);
        reporteBtnLayout.setHorizontalGroup(
            reporteBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reporteBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtReporte)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        reporteBtnLayout.setVerticalGroup(
            reporteBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reporteBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtReporte)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        prodBtn.setBackground(new java.awt.Color(153, 153, 153));
        prodBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prodBtnMouseClicked(evt);
            }
        });

        txtProducto.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtProducto.setForeground(new java.awt.Color(255, 255, 255));
        txtProducto.setText("Producto");
        txtProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout prodBtnLayout = new javax.swing.GroupLayout(prodBtn);
        prodBtn.setLayout(prodBtnLayout);
        prodBtnLayout.setHorizontalGroup(
            prodBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prodBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtProducto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        prodBtnLayout.setVerticalGroup(
            prodBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, prodBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtProducto)
                .addContainerGap())
        );

        salirBtn.setBackground(new java.awt.Color(153, 153, 153));
        salirBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirBtnMouseClicked(evt);
            }
        });

        txtSalir.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        txtSalir.setForeground(new java.awt.Color(255, 0, 51));
        txtSalir.setText("Salir");

        javax.swing.GroupLayout salirBtnLayout = new javax.swing.GroupLayout(salirBtn);
        salirBtn.setLayout(salirBtnLayout);
        salirBtnLayout.setHorizontalGroup(
            salirBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salirBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        salirBtnLayout.setVerticalGroup(
            salirBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salirBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PedidoBtn.setBackground(new java.awt.Color(153, 153, 153));
        PedidoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PedidoBtnMouseClicked(evt);
            }
        });

        txtUsuario.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setText("Pedido");
        txtUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout PedidoBtnLayout = new javax.swing.GroupLayout(PedidoBtn);
        PedidoBtn.setLayout(PedidoBtnLayout);
        PedidoBtnLayout.setHorizontalGroup(
            PedidoBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PedidoBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PedidoBtnLayout.setVerticalGroup(
            PedidoBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PedidoBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtUsuario)
                .addContainerGap())
        );

        reporteBtn2.setBackground(new java.awt.Color(153, 153, 153));
        reporteBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reporteBtn2MouseClicked(evt);
            }
        });

        txtReporte2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtReporte2.setForeground(new java.awt.Color(255, 255, 255));
        txtReporte2.setText("Clientes");

        javax.swing.GroupLayout reporteBtn2Layout = new javax.swing.GroupLayout(reporteBtn2);
        reporteBtn2.setLayout(reporteBtn2Layout);
        reporteBtn2Layout.setHorizontalGroup(
            reporteBtn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reporteBtn2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtReporte2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        reporteBtn2Layout.setVerticalGroup(
            reporteBtn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reporteBtn2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtReporte2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        usuBtn1.setBackground(new java.awt.Color(153, 153, 153));
        usuBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuBtn1MouseClicked(evt);
            }
        });

        txtUsuario1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtUsuario1.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario1.setText("Usuarios");
        txtUsuario1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout usuBtn1Layout = new javax.swing.GroupLayout(usuBtn1);
        usuBtn1.setLayout(usuBtn1Layout);
        usuBtn1Layout.setHorizontalGroup(
            usuBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuBtn1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUsuario1)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        usuBtn1Layout.setVerticalGroup(
            usuBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usuBtn1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtUsuario1)
                .addContainerGap())
        );

        javax.swing.GroupLayout FondoPanelLayout = new javax.swing.GroupLayout(FondoPanel);
        FondoPanel.setLayout(FondoPanelLayout);
        FondoPanelLayout.setHorizontalGroup(
            FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(prodBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InsumoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(proveedorBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reporteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salirBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reporteBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(PedidoBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(usuBtn1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FondoPanelLayout.setVerticalGroup(
            FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PedidoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InsumoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(proveedorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reporteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(reporteBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(salirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(FondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CerrarMouseClicked

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_minimizarMouseClicked

    private void prodBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prodBtnMouseClicked
        GestionarProducto frmProd;
        try {
            frmProd = new GestionarProducto();
            frmProd.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_prodBtnMouseClicked

    private void InsumoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsumoBtnMouseClicked
        GestionInsumo frmIns;
        try {
            frmIns = new GestionInsumo();
            frmIns.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_InsumoBtnMouseClicked

    private void proveedorBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proveedorBtnMouseClicked
        GestionarProveedor frmProv;
        try {
            frmProv = new GestionarProveedor();
            frmProv.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_proveedorBtnMouseClicked

    private void reporteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reporteBtnMouseClicked
        /*AdministracionDeReportes frmRep;
        try {
            frmRep = new AdministracionDeReportes();
            frmRep.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_reporteBtnMouseClicked

    private void salirBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_salirBtnMouseClicked

    private void PedidoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PedidoBtnMouseClicked
        // TODO add your handling code here: 
        GestionarPedido frm;
        try {
            frm = new GestionarPedido();
            frm.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PedidoBtnMouseClicked

    private void reporteBtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reporteBtn2MouseClicked
        // TODO add your handling code here:
        GestionarCliente form = new GestionarCliente();
        form.setVisible(true);
    }//GEN-LAST:event_reporteBtn2MouseClicked

    private void usuBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuBtn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_usuBtn1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VentanaPrincipal().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cerrar;
    private javax.swing.JPanel FondoPanel;
    private javax.swing.JPanel InsumoBtn;
    private javax.swing.JPanel PedidoBtn;
    private javax.swing.JPanel Titulo;
    private javax.swing.JLabel minimizar;
    private javax.swing.JPanel prodBtn;
    private javax.swing.JPanel proveedorBtn;
    private javax.swing.JPanel reporteBtn;
    private javax.swing.JPanel reporteBtn2;
    private javax.swing.JPanel salirBtn;
    private javax.swing.JLabel txtInsumo;
    private javax.swing.JLabel txtProducto;
    private javax.swing.JLabel txtProveedor;
    private javax.swing.JLabel txtReporte;
    private javax.swing.JLabel txtReporte2;
    private javax.swing.JLabel txtSalir;
    private javax.swing.JLabel txtTitulo;
    private javax.swing.JLabel txtUsuario;
    private javax.swing.JLabel txtUsuario1;
    private javax.swing.JPanel usuBtn1;
    // End of variables declaration//GEN-END:variables
}
